### PR TITLE
Bumps sdk version to last v1 version

### PR DESCRIPTION
**Pull request by Etienne-Carriere**
Manually modified file : go.mod 
Then executes : go mod vendor 

It modify go.sum and add all dependencies in vendor directory

### CODE REVIEW

**Comment by Etienne-Carriere** [comment]
Side objective is to validate the correct execution of github action on PR to master branch

**Comment by kvz** [comment]
I would request a review from @Acconut who is proficient in Go (contrary to myself) 👌

**Comment by kvz** [comment]
As to not block you, let’s make @Acconut’s review a hindsight one

**Review by Acconut — COMMENTED** [review]
Looks all fine!

**Pull request merged**
